GET http://localhost:3001/users

### partner user
POST http://localhost:3001/partners/users
Content-Type: application/json

{
  "name": "partner05",
  "email": "partiner05@gmail.com",
  "password": "123456"
}

### common user
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "common03",
  "email": "common03@gmail.com",
  "password": "123456"
}

### login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "common03@gmail.com",
  "password": "123456"
}