GET http://localhost:3001/users

### tenant user
POST http://localhost:3001/tenant
Content-Type: application/json

{
  "name": "tenant03",
  "email": "tenant03@gmail.com",
  "password": "123456"
}

### common user
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "common01",
  "email": "common01@gmail.com",
  "password": "123456",
  "tenantId": 2
}

### login tenant
POST http://localhost:3001/auth/tenant/login
Content-Type: application/json

{
  "email": "tenant03@gmail.com",
  "password": "123456"
}


### login common user

POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "common03@gmail.com",
  "password": "123456"
}

### tenant
POST http://localhost:3001/tenant
Content-Type: application/json

{
  "email": "tenant02@gmail.com",
  "password": "123456",
  "name": "tenant02"
}

### tenant users
GET http://localhost:3001/tenant/users?tenantId=2 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlbmFudDAyIiwiZW1haWwiOiJ0ZW5hbnQwMkBnbWFpbC5jb20iLCJwaG9uZSI6bnVsbCwiYWRkcmVzcyI6bnVsbCwiZGVzY3JpcHRpb24iOm51bGwsImlzQWN0aXZlIjpmYWxzZSwic3Vic2NyaXB0aW9uUGxhbiI6bnVsbCwiYmlsbGluZ0luZm9ybWF0aW9uIjpudWxsLCJsb2dvVXJsIjpudWxsLCJjcmVhdGVkQXQiOiIyMDI0LTA3LTMxVDIyOjUwOjA5LjM0NloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA3LTMxVDIyOjUwOjA5LjM0NloiLCJpYXQiOjE3MjI0Njc1NzQsImV4cCI6MTcyMjU1Mzk3NH0.c9AkH_ewZmsNc1q160ddlojgG5NBttBqBgtrIq9edxM

### vehicles create
POST http://localhost:3001/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlbmFudDAzIiwiY3JlYXRlZF9hdCI6IjIwMjQtMDgtMDRUMjE6MDI6NDguMDYxWiIsInVwZGF0ZWRfYXQiOiIyMDI0LTA4LTA0VDIxOjAyOjQ4LjA2MVoiLCJiaWxsaW5nX2luZm9ybWF0aW9uIjpudWxsLCJlbWFpbCI6InRlbmFudDAzQGdtYWlsLmNvbSIsImlzX2FjdGl2ZSI6dHJ1ZSwibG9nb191cmwiOm51bGwsImRlbGV0ZWRfYXQiOm51bGwsImRpc2FibGVkX2FjY291bnQiOm51bGwsImRvbWFpbiI6bnVsbCwiZmFjZWJvb2tfcGFnZV9pZCI6bnVsbCwiZmFjZWJvb2tfcGl4ZWwiOm51bGwsImdvb2dsZV9hbmFseXRpY3MiOm51bGwsIm5leHRfZXhwaXJhdGlvbl9kYXRlIjpudWxsLCJzaXRlX2Rlc2NyaXB0aW9uIjpudWxsLCJzaXRlX2tleV93b3JkIjpudWxsLCJzb2NpYWxfbWVkaWEiOm51bGwsInN1YmRvbWFpbiI6bnVsbCwic3Vic2NyaXB0aW9uX3BsYW5faWQiOm51bGwsInRpdGxlIjpudWxsLCJ3aGF0c2FwcF9udW1iZXIiOm51bGwsInByaW1hcnlfY29sb3IiOm51bGwsInNlY29uZGFyeV9jb2xvciI6bnVsbCwiaWF0IjoxNzIyODA1Mzg3LCJleHAiOjE3MjI4OTE3ODd9.Cs4nKkY_HlhisMih-TJA8yB6RbI9Lz_QIrTEt-VjBPs

{
  "vehicle_owner": "partner03",
  "vehicle_price": 10000,
  "vehicle_title": "vehicle02",
  "title": "vehicle02",
  "description": "vehicle02",
  "status": "active",
  "city": "city01",
  "vehicle_brand_id":1
}

### vehicles findAll
GET http://localhost:3001/vehicles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6InRlbmFudDAzIiwiY3JlYXRlZF9hdCI6IjIwMjQtMDgtMDRUMjE6MDI6NDguMDYxWiIsInVwZGF0ZWRfYXQiOiIyMDI0LTA4LTA0VDIxOjAyOjQ4LjA2MVoiLCJiaWxsaW5nX2luZm9ybWF0aW9uIjpudWxsLCJlbWFpbCI6InRlbmFudDAzQGdtYWlsLmNvbSIsImlzX2FjdGl2ZSI6dHJ1ZSwibG9nb191cmwiOm51bGwsImRlbGV0ZWRfYXQiOm51bGwsImRpc2FibGVkX2FjY291bnQiOm51bGwsImRvbWFpbiI6bnVsbCwiZmFjZWJvb2tfcGFnZV9pZCI6bnVsbCwiZmFjZWJvb2tfcGl4ZWwiOm51bGwsImdvb2dsZV9hbmFseXRpY3MiOm51bGwsIm5leHRfZXhwaXJhdGlvbl9kYXRlIjpudWxsLCJzaXRlX2Rlc2NyaXB0aW9uIjpudWxsLCJzaXRlX2tleV93b3JkIjpudWxsLCJzb2NpYWxfbWVkaWEiOm51bGwsInN1YmRvbWFpbiI6bnVsbCwic3Vic2NyaXB0aW9uX3BsYW5faWQiOm51bGwsInRpdGxlIjpudWxsLCJ3aGF0c2FwcF9udW1iZXIiOm51bGwsInByaW1hcnlfY29sb3IiOm51bGwsInNlY29uZGFyeV9jb2xvciI6bnVsbCwiaWF0IjoxNzIyODA1Mzg3LCJleHAiOjE3MjI4OTE3ODd9.Cs4nKkY_HlhisMih-TJA8yB6RbI9Lz_QIrTEt-VjBPs


### vehicles brand
GET  http://localhost:3001/brand
Content-Type: application/json

### vehicles versions
GET  http://localhost:3001/versions
Content-Type: application/json

### vehicles category
GET  http://localhost:3001/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlbmFudDAyIiwiY3JlYXRlZF9hdCI6IjIwMjQtMDgtMDRUMjA6NTA6NDYuNTQ4WiIsInVwZGF0ZWRfYXQiOiIyMDI0LTA4LTA0VDIwOjUwOjQ2LjU0OFoiLCJiaWxsaW5nX2luZm9ybWF0aW9uIjpudWxsLCJlbWFpbCI6InRlbmFudDAyQGdtYWlsLmNvbSIsImlzX2FjdGl2ZSI6dHJ1ZSwibG9nb191cmwiOm51bGwsImRlbGV0ZWRfYXQiOm51bGwsImRpc2FibGVkX2FjY291bnQiOm51bGwsImRvbWFpbiI6bnVsbCwiZmFjZWJvb2tfcGFnZV9pZCI6bnVsbCwiZmFjZWJvb2tfcGl4ZWwiOm51bGwsImdvb2dsZV9hbmFseXRpY3MiOm51bGwsIm5leHRfZXhwaXJhdGlvbl9kYXRlIjpudWxsLCJzaXRlX2Rlc2NyaXB0aW9uIjpudWxsLCJzaXRlX2tleV93b3JkIjpudWxsLCJzb2NpYWxfbWVkaWEiOm51bGwsInN1YmRvbWFpbiI6bnVsbCwic3Vic2NyaXB0aW9uX3BsYW5faWQiOm51bGwsInRpdGxlIjpudWxsLCJ3aGF0c2FwcF9udW1iZXIiOm51bGwsInByaW1hcnlfY29sb3IiOm51bGwsInNlY29uZGFyeV9jb2xvciI6bnVsbCwiaWF0IjoxNzIzMDYzNTg2LCJleHAiOjE3MjMxNDk5ODZ9.RMf96LOkc6SnwgadMUH4_OO5yFNcTcy5Kywc5SjjDsE

