GET http://localhost:3001/users

### partner user
POST http://localhost:3001/partners/users
Content-Type: application/json

{
  "name": "partner05",
  "email": "partiner05@gmail.com",
  "password": "123456"
}

### common user
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "common01",
  "email": "common01@gmail.com",
  "password": "123456",
  "tenantId": 2
}

### login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "common03@gmail.com",
  "password": "123456"
}

### tenant
POST http://localhost:3001/tenant
Content-Type: application/json

{
  "email": "tenant02@gmail.com",
  "password": "123456",
  "name": "tenant02"
}