import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Exemplo de criação de um usuário
  await prisma.vehicleBrand.createMany({
    data: [
      { label: 'CITROEN', value: 16 },
      { label: 'FIAT', value: 25 },
      { label: 'FORD', value: 27 },
      { label: 'GM - CHEVROLET', value: 29 },
      { label: 'HONDA', value: 33 },
      { label: 'HYUNDAI', value: 34 },
      { label: 'JAC', value: 36 },
      { label: 'KIA MOTORS', value: 41 },
      { label: 'NISSAN', value: 59 },
      { label: 'PEUGEOT', value: 60 },
      { label: 'RENAULT', value: 64 },
      { label: 'TOYOTA', value: 73 },
      { label: 'VW - VOLKSWAGEN', value: 75 },
      { label: 'AM GEN', value: 1 },
      { label: 'MCLAREN', value: 2 },
      { label: 'AGRALE', value: 3 },
      { label: 'ALFA ROMEO', value: 4 },
      { label: 'ASIA MOTORS', value: 5 },
      { label: 'AUDI', value: 6 },
      { label: 'BMW', value: 7 },
      { label: 'BRM', value: 8 },
      { label: 'BUGGY', value: 9 },
      { label: 'BUGRE', value: 10 },
      { label: 'CBT JIPE', value: 11 },
      { label: 'CHANGAN', value: 12 },
      { label: 'CHERY', value: 13 },
      { label: 'CADILLAC', value: 14 },
      { label: 'CHRYSLER', value: 15 },
      { label: 'CROSS LANDER', value: 17 },
      { label: 'DAEWOO', value: 18 },
      { label: 'DAIHATSU', value: 19 },
      { label: 'DODGE', value: 20 },
      { label: 'EFFA', value: 21 },
      { label: 'ENGESA', value: 22 },
      { label: 'ENVEMO', value: 23 },
      { label: 'FERRARI', value: 24 },
      { label: 'FIBRAVAN', value: 26 },
      { label: 'FYBER', value: 28 },
      { label: 'GREAT WALL', value: 30 },
      { label: 'GURGEL', value: 31 },
      { label: 'HAFEI', value: 32 },
      { label: 'ISUZU', value: 35 },
      { label: 'JINBEI', value: 37 },
      { label: 'JPX', value: 38 },
      { label: 'JAGUAR', value: 39 },
      { label: 'JEEP', value: 40 },
      { label: 'LAMBORGHINI', value: 42 },
      { label: 'LIFAN', value: 43 },
      { label: 'LOBINI', value: 44 },
      { label: 'LADA', value: 45 },
      { label: 'LAND ROVER', value: 46 },
      { label: 'LEXUS', value: 47 },
      { label: 'LOTUS', value: 48 },
      { label: 'MG', value: 49 },
      { label: 'MINI', value: 50 },
      { label: 'MAHINDRA', value: 51 },
      { label: 'MASERATI', value: 52 },
      { label: 'MATRA', value: 53 },
      { label: 'MAZDA', value: 54 },
      { label: 'MERCEDES-BENZ', value: 55 },
      { label: 'MERCURY', value: 56 },
      { label: 'MITSUBISHI', value: 57 },
      { label: 'MIURA', value: 58 },
      { label: 'PLYMOUTH', value: 61 },
      { label: 'PONTIAC', value: 62 },
      { label: 'PORSCHE', value: 63 },
      { label: 'ROVER', value: 65 },
      { label: 'SSANGYONG', value: 66 },
      { label: 'SAAB', value: 67 },
      { label: 'SATURN', value: 68 },
      { label: 'SEAT', value: 69 },
      { label: 'SUBARU', value: 70 },
      { label: 'SUZUKI', value: 71 },
      { label: 'TAC', value: 72 },
      { label: 'TROLLER', value: 74 },
      { label: 'VOLVO', value: 76 },
      { label: 'WAKE', value: 77 },
      { label: 'WALK', value: 78 },
      { label: 'SMART', value: 79 },
      { label: 'SHINERAY', value: 80 },
      { label: 'ASTON MARTIN', value: 81 },
      { label: 'FOTON', value: 82 },
      { label: 'RELY', value: 83 },
      { label: 'ROLLS-ROYCE', value: 84 },
      { label: 'DKW VEMAG', value: 85 },
      { label: 'LANDWIND', value: 86 },
      { label: 'GEELY', value: 87 },
      { label: 'CHANA', value: 88 },
      { label: 'PUMA', value: 89 },
      { label: 'RAM', value: 90 },
      { label: 'INFINITI', value: 91 },
      { label: 'TESLA', value: 92 },
      { label: 'BABY', value: 93 },
      { label: 'IVECO', value: 94 },
      { label: 'ACURA', value: 95 },
      { label: 'HITECH ELETRIC', value: 96 },
      { label: 'DUCATI', value: 1 },
      { label: 'BUELL', value: 2 },
      { label: 'KTM', value: 3 },
      { label: 'KAHENA', value: 4 },
      { label: 'FOX', value: 5 },
      { label: 'MRX', value: 6 },
      { label: 'YAMAHA', value: 7 },
      { label: 'IROS', value: 8 },
      { label: 'SUZUKI', value: 9 },
      { label: 'TRIUMPH', value: 10 },
      { label: "L'AQUILA", value: 11 },
      { label: 'SUNDOWN', value: 12 },
      { label: 'DAELIM', value: 13 },
      { label: 'AMAZONAS', value: 14 },
      { label: 'HONDA', value: 15 },
      { label: 'HERO', value: 16 },
      { label: 'APRILIA', value: 17 },
      { label: 'JONNY', value: 18 },
      { label: 'DERBI', value: 19 },
      { label: 'ADLY', value: 20 },
      { label: 'KAWASAKI', value: 21 },
      { label: 'ORCA', value: 22 },
      { label: 'DAFRA', value: 23 },
      { label: 'JOHNNYPAG', value: 24 },
      { label: 'PIAGGIO', value: 25 },
      { label: 'MVK', value: 26 },
      { label: 'REGAL RAPTOR', value: 27 },
      { label: 'HARLEY-DAVIDSON', value: 28 },
      { label: 'PEGASSI', value: 29 },
      { label: 'MV AGUSTA', value: 30 },
      { label: 'PEUGEOT', value: 31 },
      { label: 'ATALA', value: 32 },
      { label: 'MOTO GUZZI', value: 33 },
    ],
    skipDuplicates: true, // Isso evita erros se você tentar inserir dados que já existem
  })
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
