import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Exemplo de criação de um usuário
  await prisma.vehicleBrand.createMany({
    data: [
      { name: 'CITROEN', value: 16 },
      { name: 'FIAT', value: 25 },
      { name: 'FORD', value: 27 },
      { name: 'GM - CHEVROLET', value: 29 },
      { name: 'HONDA', value: 33 },
      { name: 'HYUNDAI', value: 34 },
      { name: 'JAC', value: 36 },
      { name: 'KIA MOTORS', value: 41 },
      { name: 'NISSAN', value: 59 },
      { name: 'PEUGEOT', value: 60 },
      { name: 'RENAULT', value: 64 },
      { name: 'TOYOTA', value: 73 },
      { name: 'VW - VOLKSWAGEN', value: 75 },
      { name: 'AM GEN', value: 1 },
      { name: 'MCLAREN', value: 2 },
      { name: 'AGRALE', value: 3 },
      { name: 'ALFA ROMEO', value: 4 },
      { name: 'ASIA MOTORS', value: 5 },
      { name: 'AUDI', value: 6 },
      { name: 'BMW', value: 7 },
      { name: 'BRM', value: 8 },
      { name: 'BUGGY', value: 9 },
      { name: 'BUGRE', value: 10 },
      { name: 'CBT JIPE', value: 11 },
      { name: 'CHANGAN', value: 12 },
      { name: 'CHERY', value: 13 },
      { name: 'CADILLAC', value: 14 },
      { name: 'CHRYSLER', value: 15 },
      { name: 'CROSS LANDER', value: 17 },
      { name: 'DAEWOO', value: 18 },
      { name: 'DAIHATSU', value: 19 },
      { name: 'DODGE', value: 20 },
      { name: 'EFFA', value: 21 },
      { name: 'ENGESA', value: 22 },
      { name: 'ENVEMO', value: 23 },
      { name: 'FERRARI', value: 24 },
      { name: 'FIBRAVAN', value: 26 },
      { name: 'FYBER', value: 28 },
      { name: 'GREAT WALL', value: 30 },
      { name: 'GURGEL', value: 31 },
      { name: 'HAFEI', value: 32 },
      { name: 'ISUZU', value: 35 },
      { name: 'JINBEI', value: 37 },
      { name: 'JPX', value: 38 },
      { name: 'JAGUAR', value: 39 },
      { name: 'JEEP', value: 40 },
      { name: 'LAMBORGHINI', value: 42 },
      { name: 'LIFAN', value: 43 },
      { name: 'LOBINI', value: 44 },
      { name: 'LADA', value: 45 },
      { name: 'LAND ROVER', value: 46 },
      { name: 'LEXUS', value: 47 },
      { name: 'LOTUS', value: 48 },
      { name: 'MG', value: 49 },
      { name: 'MINI', value: 50 },
      { name: 'MAHINDRA', value: 51 },
      { name: 'MASERATI', value: 52 },
      { name: 'MATRA', value: 53 },
      { name: 'MAZDA', value: 54 },
      { name: 'MERCEDES-BENZ', value: 55 },
      { name: 'MERCURY', value: 56 },
      { name: 'MITSUBISHI', value: 57 },
      { name: 'MIURA', value: 58 },
      { name: 'PLYMOUTH', value: 61 },
      { name: 'PONTIAC', value: 62 },
      { name: 'PORSCHE', value: 63 },
      { name: 'ROVER', value: 65 },
      { name: 'SSANGYONG', value: 66 },
      { name: 'SAAB', value: 67 },
      { name: 'SATURN', value: 68 },
      { name: 'SEAT', value: 69 },
      { name: 'SUBARU', value: 70 },
      { name: 'SUZUKI', value: 71 },
      { name: 'TAC', value: 72 },
      { name: 'TROLLER', value: 74 },
      { name: 'VOLVO', value: 76 },
      { name: 'WAKE', value: 77 },
      { name: 'WALK', value: 78 },
      { name: 'SMART', value: 79 },
      { name: 'SHINERAY', value: 80 },
      { name: 'ASTON MARTIN', value: 81 },
      { name: 'FOTON', value: 82 },
      { name: 'RELY', value: 83 },
      { name: 'ROLLS-ROYCE', value: 84 },
      { name: 'DKW VEMAG', value: 85 },
      { name: 'LANDWIND', value: 86 },
      { name: 'GEELY', value: 87 },
      { name: 'CHANA', value: 88 },
      { name: 'PUMA', value: 89 },
      { name: 'RAM', value: 90 },
      { name: 'INFINITI', value: 91 },
      { name: 'TESLA', value: 92 },
      { name: 'BABY', value: 93 },
      { name: 'IVECO', value: 94 },
      { name: 'ACURA', value: 95 },
      { name: 'HITECH ELETRIC', value: 96 },
      { name: 'DUCATI', value: 1 },
      { name: 'BUELL', value: 2 },
      { name: 'KTM', value: 3 },
      { name: 'KAHENA', value: 4 },
      { name: 'FOX', value: 5 },
      { name: 'MRX', value: 6 },
      { name: 'YAMAHA', value: 7 },
      { name: 'IROS', value: 8 },
      { name: 'SUZUKI', value: 9 },
      { name: 'TRIUMPH', value: 10 },
      { name: "L'AQUILA", value: 11 },
      { name: 'SUNDOWN', value: 12 },
      { name: 'DAELIM', value: 13 },
      { name: 'AMAZONAS', value: 14 },
      { name: 'HONDA', value: 15 },
      { name: 'HERO', value: 16 },
      { name: 'APRILIA', value: 17 },
      { name: 'JONNY', value: 18 },
      { name: 'DERBI', value: 19 },
      { name: 'ADLY', value: 20 },
      { name: 'KAWASAKI', value: 21 },
      { name: 'ORCA', value: 22 },
      { name: 'DAFRA', value: 23 },
      { name: 'JOHNNYPAG', value: 24 },
      { name: 'PIAGGIO', value: 25 },
      { name: 'MVK', value: 26 },
      { name: 'REGAL RAPTOR', value: 27 },
      { name: 'HARLEY-DAVIDSON', value: 28 },
      { name: 'PEGASSI', value: 29 },
      { name: 'MV AGUSTA', value: 30 },
      { name: 'PEUGEOT', value: 31 },
      { name: 'ATALA', value: 32 },
      { name: 'MOTO GUZZI', value: 33 },
    ],
    skipDuplicates: true, // Isso evita erros se você tentar inserir dados que já existem
  })
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
